Adds indexes to generated tables
CluedIn-io/CluedIn.Connector.SqlServer pull request #13
Opened 2021-05-10 10:46 UTC by BenFidge

Fixes #12

2021-05-10 13:27 UTC, Kieranties requested changes

2021-05-10 13:29 UTC, BenFidge commented on src/Connector.SqlServer/Features/DefaultBuildCreateContainerFeature.cs
> +
Yep that's fine will do

2021-05-10 13:46 UTC, Kieranties commented on src/Connector.SqlServer/Features/DefaultBuildCreateContainerFeature.cs
> +            return "nvarchar(1024)";
We'll need to revert this and make sure we manage index creation on allowed columns, or generated our indexes through another means.

2021-05-10 13:58 UTC, Kieranties requested changes

2021-05-10 13:58 UTC, Kieranties commented on src/Connector.SqlServer/Features/DefaultBuildCreateContainerFeature.cs
> +            return "nvarchar(1024)";
@lju is currently doing this:
```
ALTER TABLE dbo.KontraktEkspressPersonFull ALTER COLUMN OriginEntityCode NVARCHAR(1024) 
ALTER TABLE dbo.KontraktEkspressProductFull ALTER COLUMN OriginEntityCode NVARCHAR(1024) 
ALTER TABLE dbo.KontraktEkspressPersonFullEdges ALTER COLUMN OriginEntityCode NVARCHAR(1024) 
ALTER TABLE dbo.KontraktEkspressProductFullEdges ALTER COLUMN OriginEntityCode NVARCHAR(1024) 
CREATE UNIQUE INDEX idx_entityCode
ON dbo.KontraktEkspressPersonFull (OriginEntityCode); 
CREATE UNIQUE INDEX idx_entityCode
ON dbo.KontraktEkspressProductFull (OriginEntityCode); 
CREATE INDEX idx_entityCode
ON dbo.KontraktEkspressPersonFullEdges (OriginEntityCode); 
CREATE INDEX idx_entityCode
ON dbo.KontraktEkspressProductFullEdges (OriginEntityCode); 
```

Could we ensure that for know column names (like originentitycode) we enforce a specific db type? In this case nvarchar(1024)

2021-05-14 13:44 UTC, Kieranties approved these changes

2021-05-14 13:44 UTC, merged