Add time stamp column to sync mode
CluedIn-io/CluedIn.Connector.SqlServer pull request #25
Opened 2021-08-17 06:35 UTC by BenFidge

Fixes #2762

As per Lukas request, `Sync` mode now outputs `TimeStamp` field by default

2021-08-17 10:06 UTC, Kieranties requested changes
@BenFidge For the default sync mode, with the new column being added - what will happen for existing stream tables from 3.2.4? I assume it will blow up?

We need to make sure that existing stream tables can still be written to, ideally without having to re-process all the data.

2021-08-18 00:55 UTC, BenFidge commented on GitVersion.yml
> +next-version: 3.3
Not sure how that happened!

2021-08-19 07:26 UTC, Kieranties commented on docs/3.2.5-release-notes.md
> ++ Sync mode now adds `TimeStamp` field by default
@BenFidge We do need a release note here - you are changing the default implementation.  Please add the line as suggested

2021-08-20 01:47 UTC, BenFidge commented
Relies on main repo [PR 2774](https://github.com/CluedIn-io/CluedIn/pull/2774)

2021-09-01 08:37 UTC, Kieranties commented
/azp run

2021-09-06 08:32 UTC, merged