feat: Implement IConnectorV2
CluedIn-io/CluedIn.Connector.SqlServer pull request #77
Opened 2023-04-25 08:36 UTC by AndreasNicolaisen

2023-06-16 12:23 UTC, zvirja requested changes
Brilliant work 🤩 Was a pleasure to read your code!!! I love the design of it and how easy it's to follow. Awesome! 🥇 

Now let's hope that harsh reality and performance testing will not force you squash all those descriptive bits into one big query 😟 

I didn't test your code and just did a surface spell-checking review. See my suggestions below.

2023-06-16 12:23 UTC, zvirja commented on src/Connector.SqlServer/Utils/TableDefinitions/CodeTableDefinition.cs
> +            var mode = streamModel.Mode ?? StreamMode.Sync; // TODO: Correct fallback?
What is the case when it's empty? 
I think we should make the decision and remove TODO. If not us now, who will know better in future? :)

2023-06-19 10:58 UTC, AndreasNicolaisen commented on src/Connector.SqlServer/Connector/SqlServerConnector.cs
> +        public override async Task EmptyContainer(ExecutionContext executionContext, IReadOnlyStreamModel streamModel)
Change to execute command for each table.

2023-06-19 10:59 UTC, AndreasNicolaisen commented on src/Connector.SqlServer/Connector/SqlServerConnector.cs
>              var transaction = connectionAndTransaction.Transaction;
Agreed, changed to use LINQ.

2023-06-19 11:11 UTC, AndreasNicolaisen commented on src/Connector.SqlServer/Connector/SqlServerConnector.cs
> +        public override async Task<IEnumerable<IConnectorContainer>> GetContainers(ExecutionContext executionContext, Guid connectorProviderDefinitionId)
Maybe we should, I am not sure what this the result of this function is used for. In platform, its only usage is in [`ConnectorController`](https://github.com/CluedIn-io/CluedIn/blob/develop/Code/Server.WebApi/Controllers/Consume/Connectors/ConnectorController.cs#L41), were it simply returns the result. I can't find any place in the UI were it's used, so can't tell for sure what is expected.

2023-06-19 12:05 UTC, zvirja commented on src/Connector.SqlServer/Connector/SqlServerConnector.cs
> +                await transaction.CommitAsync();
Should we than run some dummy query? Like `SELECT 1 FROM <table>` or similar?

2023-06-19 12:19 UTC, AndreasNicolaisen commented on src/Connector.SqlServer/Connector/SqlServerConnector.cs
> +                await transaction.CommitAsync();
Good idea, added dummy select query from main table.

2023-06-20 08:36 UTC, AndreasNicolaisen commented on src/Connector.SqlServer/Connector/SqlServerConnector.cs
> +        public override async Task<IEnumerable<IConnectorContainer>> GetContainers(ExecutionContext executionContext, Guid connectorProviderDefinitionId)
Added filtering down to only yield main table. The way I'm doing this, is to find tables, that have the columns, that a main table as a minimum would have. If we change what those are, we might need to rework this.

2023-06-26 09:29 UTC, Hyldahl approved these changes
Looks good 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀

2023-06-26 10:18 UTC, zvirja approved these changes

2023-06-26 13:47 UTC, zvirja approved these changes

2023-06-26 13:48 UTC, merged