feat: Add `IsDataPartOriginEntityCode ` column on code table
CluedIn-io/CluedIn.Connector.SqlServer pull request #99
Opened 2023-09-19 09:06 UTC by AndreasNicolaisen

## Description

Work Item ID: AB#27203

Add `IsDataPartOriginEntityCode` column to code table. This will indicate if the code is the origin code of any data parts, in the entity being export. The column will be added to existing tables, and is therefore nullable.

Also refactor upgrade code, to be in separate classes.

Also adding archiving of custom table types. since this version will not work with old custom table type.

## Test approach 
Update reference, observe that `IsDataPartOriginEntityCode` column is present, and filled with nulls.
Export entities, and observe that `IsDataPartOriginEntityCode` is set.

Unit tests are also added/adjusted.

## Release Note 
feat: Add `IsDataPartOriginEntityCode` column to codes table, to indicate if entitycode is the origin code of at least one datapart.

2023-09-19 10:29 UTC, Hyldahl requested changes
Can we add release upgrade notes like we did with the previous release?

2023-09-19 14:27 UTC, zvirja reviewed
I left a bit of generic comments I spotted. I have a bit limited knowledge, so hope it makes at least some sense.

Some things to consider:
- Make sure that schema is always considered. There could be two tables with the same name in DB and differ only by schema. Make sure all code is ready for that and will not fail.
- I found that some upgrade utilities here and there rename tables in DB. Can't we re-use the existing archiving logic? Feel like we format archived table name a few times and it could lead to inconsistencies with further refactorings

Otherwise see the comments below

2023-09-19 14:27 UTC, zvirja commented on src/Connector.SqlServer/Utils/Upgrade/UpgradeTo370Utility.cs
> +                           tables.Name = '{mainTableName.LocalName}' AND
should we also check for schema name?

2023-09-19 14:27 UTC, zvirja commented on src/Connector.SqlServer/Utils/Upgrade/UpgradeTo370Utility.cs
> +                        .GetColumnDefinitions(StreamMode.Sync, Array.Empty<(string, ConnectorPropertyDataType)>())
Is that OK to hardcode sync mode?

2023-09-19 14:27 UTC, zvirja commented on src/Connector.SqlServer/Utils/TableDefinitions/EntityCodeExtensions.cs
> +    public static object IsOriginEntityCode(this IEntityCode code)
nit: Name looks a bit weird, as it return either `bool` or `DBNull.Value`. Should it be normalized to DbValue or something and later reflected somehow in the name?

2023-09-19 14:27 UTC, zvirja commented on src/Connector.SqlServer/Utils/Upgrade/UpgradeCodeTableUtility.cs
> +                WHERE TABLE_NAME = N'{codeTableName.LocalName}'
Review whether schema should also be compared, as you could have same name in different schemas

2023-09-22 15:18 UTC, Hyldahl approved these changes

2023-09-22 15:28 UTC, merged